import { Constants } from '../../constants';
import { GeneratedCodeDisclaimer } from '../private/generated-doc-data';

export function buildGeneratedCodeDisclaimerComment(generatedCodeDisclaimer: GeneratedCodeDisclaimer) {
  let comment = `\
// Generated by turbogate (v${Constants.VERSION})
// BEFORE EDITING: Please read turbogate docs and the following caveats.`;

  if (generatedCodeDisclaimer.purpose) {
    comment += `
// Purpose of thise file:           ${generatedCodeDisclaimer.purpose}`;
  }

  if (generatedCodeDisclaimer.expectedSignature) {
    comment += `
// Expected signature:              ${generatedCodeDisclaimer.expectedSignature}`;
  }

  if (generatedCodeDisclaimer.canBeEdited) {
    comment += `
// Can be edited?                   ${generatedCodeDisclaimer.canBeEdited}`;
  }

  if (generatedCodeDisclaimer.canBePermanentlyDeleted) {
    comment += `
// Can be permanently deleted?      ${generatedCodeDisclaimer.canBePermanentlyDeleted}`;
  }

  if (generatedCodeDisclaimer.willBeRecreated) {
    comment += `
// Will be recreated?               ${generatedCodeDisclaimer.willBeRecreated}`;
  }

  return comment;
}
